Task4 add basic game logic
daria-bnn/the-card-game pull request #4
Opened 2022-05-13 19:45 UTC by daria-bnn

2022-05-20 06:56 UTC, mrerberg requested changes

2022-05-20 06:56 UTC, mrerberg commented on webpack.config.js
> +        // new CopyPlugin({
Если код не нужен, можешь смело удалить

2022-05-20 06:56 UTC, mrerberg commented on webpack.config.js
> +    mode: process.env.NODE_ENV,
mode: process.env.NODE_ENV ||  "development"

Таким образом, можно будет не передавать всегда development

2022-05-20 06:56 UTC, mrerberg commented on src/js/render-function.js
> +function createTempleteCart(block) {
Функция и файл различаются кардинально по названиям. Я бы назвал файл по названию функции

2022-05-20 06:56 UTC, mrerberg commented on src/js/index.js
> +window.application.blocks['create-form'] = createForm;
Наполни объект выше, зачем это выносить сюда? Или ты так разделила дефолтное состояние от наполеннного?

2022-05-20 06:56 UTC, mrerberg commented on src/js/html-elements.js
> +function blockForm() {
Я бы завел отдельную папку blocks и вынес бы каждый блок в свой файл, такая структура мне кажется более очевидной

2022-05-20 06:56 UTC, mrerberg commented on src/js/global-object-application.js
> +window.application = {
Зачем тебе еще 1 состояние? Или ты его пыталась сделать здесь и импортировать в index.js?

2022-05-20 06:56 UTC, mrerberg commented on src/js/global-object-application.js
> +window.application = {
Если да, но ты можешь это обернуть в функцию и ее экспортировать. Будет что-то типа `initGameState()`

2022-05-20 06:56 UTC, mrerberg commented on src/js/functions.js
> +function checkCards() {
У тебя в 1 файле есть и бизнес логика (логика самой игры) и утилитарная логика, например, makeButtonInactive. Эти две логики стоит отделять друг от друга. Я бы поместил утилитарные функции в файл/папку utils, а для бизнес логики придумал бы другой файл/папку. Не стоит мешать концепции и зоны отвественности в 1 месте

2022-05-20 06:56 UTC, mrerberg commented on src/js/functions.js
> +//создание рандомного массива карт
Мне кажется, что зачастую тут лишние комменты, код может говорить сам за себя

2022-05-20 06:56 UTC, mrerberg commented on src/js/create-cards-value.js
> +        cardValue.forEach((value) => {
Цикл в цикле? Сложность данного алгоритма квадратичная, не хорошо. Можно обойтись 1 циклом, или 2 циклами, но они идут по очереди

2022-05-20 06:57 UTC, mrerberg commented
В целом, у тебя хорошо получается! Есть небольшие косяки, но это поправимо

2022-05-22 15:25 UTC, mrerberg requested changes

2022-05-22 15:25 UTC, mrerberg commented on webpack.config.js
> +// const CopyPlugin = require("copy-webpack-plugin");
Ненужный код удаляем)

2022-05-22 15:25 UTC, mrerberg commented on src/js/create-template-card.js
> +function createTempleteCart(block) {
Можно так

```js
export function createTempleteCart()
```

Так проще, чем в конце указывать экспортируемый функции

2022-05-22 15:25 UTC, mrerberg commented on src/js/info-about-levels-game.js
> +function levelsGame() {
Я бы в названии обыграл 2 момента точно: что это функция инициализирует и инициализирует какое-то состояние, это очень важно, так как это логика игры

```js
initGameLevesState
```

2022-05-22 15:25 UTC, mrerberg commented on src/js/init-game-state.js
> +function initGameState() {
Почему у тебя есть данный стейт, а уровни сложности выделены в отдельный стейт? Это окей бить стейты на разные, просто спрашиваю)

2022-05-22 15:25 UTC, mrerberg commented on src/js/init-game-state.js
> +function initGameState() {
Рекомендую все функции для стейда занести в папку `state`. Привыкай делать четкую и кричащую за себя структуру

2022-05-22 15:25 UTC, mrerberg commented on src/index.html
> +<html lang="en">
Разве сайт на английском?

2022-05-22 16:55 UTC, daria-bnn commented on webpack.config.js
> +// const CopyPlugin = require("copy-webpack-plugin");
Исправила

2022-05-22 16:56 UTC, daria-bnn commented on src/js/create-template-card.js
> +function createTempleteCart(block) {
Исправила

2022-05-22 16:56 UTC, daria-bnn commented on src/js/info-about-levels-game.js
> +function levelsGame() {
Изменила название на initGameLevesState

2022-05-22 16:56 UTC, daria-bnn commented on src/js/init-game-state.js
> +function initGameState() {
Подумала, что они по смыслу различаются и решила также для удобства не класть их вместе, так как объект с уровнями сложности я в дальнейшем думаю дополнить еще доп. информацией (например, для каждого уровня сложности - разное колличество попыток на ошибку) 
Может быть тогда для **initGameState** нужно более индивидуальное название, раз у меня несколько файлов о состоянии игры?

2022-05-22 16:56 UTC, daria-bnn commented on src/js/init-game-state.js
> +function initGameState() {
Создала папку **state** и посместила туда _...levels-state_ и _...game-state_

2022-05-22 16:57 UTC, daria-bnn commented on src/index.html
> +<html lang="en">
Исправила на lang="ru"

2022-05-23 07:21 UTC, mrerberg commented on src/js/init-game-state.js
> +function initGameState() {
Я думаю, что можно оставить такое название, просто в рамках данной функции запускать уже частные случаи инициализации стейта

2022-05-23 07:23 UTC, mrerberg approved these changes

2022-05-23 07:23 UTC, mrerberg commented on src/js/state/init-game-leves-state.js
> +        light: 3,
Сейчас не очевидно, что означают данные цифры. Я бы дал уточнение так

```js
{
  light: {
       cardsPairs: 3,
   }
}
```

2022-05-23 07:24 UTC, mrerberg commented on package.json
> +        "dev": "NODE_ENV=development webpack"
А зачем тебе данная команда? Она не нужна, у тебя же есть build и start

2022-05-24 11:47 UTC, daria-bnn commented on package.json
> +        "dev": "NODE_ENV=development webpack"
Ок, удалила dev

2022-05-24 11:47 UTC, daria-bnn commented on src/js/state/init-game-leves-state.js
> +        light: 3,
В следующей редакции игры отредактировала этот объект и дала уточнения по названиям

2022-10-25 18:06 UTC, merged