Task5 TypeScript
daria-bnn/the-card-game pull request #5
Opened 2022-05-24 11:41 UTC by daria-bnn

Проект был переведен на TypeScript.
Были добавлены экраны с результатом игры, которые будет видеть пользователь при проигрыше/победе. Также в интерфейс выведена информация о колличестве попыток.

2022-05-26 07:18 UTC, mrerberg requested changes

2022-05-26 07:18 UTC, mrerberg commented on src/styles/_first-page.scss
> +        border: 1px solid #757578;
Рекомендую пользоваться scss переменными

2022-05-26 07:18 UTC, mrerberg commented on src/styles/_global.scss
> +    src: url('../fonts/Rubik-VariableFont_wght.ttf');
Есть два более оптимальных по весу и качества форматов шрифта woff/woff2

2022-05-26 07:18 UTC, mrerberg commented on src/styles/_page-with-cards.scss
> +// .block-game__card-wrapper_background .card-block__background {
Почему линтер не ругается на мертвый код? Надо донастроить)

2022-05-26 07:18 UTC, mrerberg commented on src/ts/blocks-html/cards-element.ts
> +function cardsElement(card) {
export function cardsElement

Так проще)

2022-05-26 07:18 UTC, mrerberg commented on src/ts/blocks-html/result-block-element.ts
> +export function blockResult(image, result: string) {
`result` используется как content, а бы переименовал аргумент

2022-05-26 07:18 UTC, mrerberg commented on src/ts/blocks.ts
> +const ImgWin = require('../img/win.png');
А какая ошибка падает? Ты помнишь про решение через index.d.ts файл?

2022-05-26 07:18 UTC, mrerberg commented on src/ts/blocks.ts
> +    const form: HTMLFormElement | null = container.querySelector('.form');
А ты думаешь, тут стоит описывать тип явно? Он же в данном случае автоматом вычислится

2022-05-26 07:18 UTC, mrerberg commented on src/ts/blocks.ts
> +                    input.value === 'light' ||
Чтобы прокачаться, я рекомендую почитать тебе и применить сюда https://www.typescriptlang.org/docs/handbook/enums.html

Либо создать тип со всеми уровнями сложностей

2022-05-26 07:18 UTC, mrerberg commented on src/ts/blocks.ts
> +        inputs.forEach((input) => {
А ты слышала про https://learn.javascript.ru/event-bubbling?

Это способ повесить обработчик на общий для всех элементов контейнер, чтобы не вешать на каждый отдельный инпут

2022-05-26 07:18 UTC, mrerberg commented on src/ts/blocks.ts
> +export function createButton(container: HTMLDivElement) {
У тебя в 1 файле очень много функций, как мне кажется. Я бы сделал папку blocks, а в ней бы уже хранил файлики. И в каждом файлике по функции. Ну или по смыслу объединял в файлики. Суть в том, что данный файл слишком большой

2022-05-26 07:18 UTC, mrerberg commented on src/ts/create-cards-value.ts
> +type Card = {
Можно создать для типов отдельный файл types.ts. Так делают. Либо папку types, а там уже по файлам разбивают. Чтобы можно было посмотреть, какие для программы есть общие типы

2022-05-26 07:18 UTC, mrerberg commented on src/ts/create-cards-value.ts
> +function createCardValues(cardSuit: Card[], cardValue: string[]): CardResult[] {
cardSuit -> cardSuits
cardValue -> cardValues

2022-05-26 07:18 UTC, mrerberg commented on src/ts/index.ts
> +        application: any;
Тут я бы задал тип, это важная часть программы

2022-05-26 07:18 UTC, mrerberg commented on src/ts/main-logic-game.ts
> +type OneCard = {
У тебя же уже есть тип `CardResult`

И я бы CardResult переименовал бы в  Card

2022-05-26 07:18 UTC, mrerberg commented on src/ts/template-engine/create-template-card.ts
> +export function createTempleteCart(block: any) {
Тут бы я затипизовал аргумент block

2022-05-26 07:18 UTC, mrerberg commented on src/ts/utils/utils.ts
> +export function makeButtonInactive(button: HTMLButtonElement | null): void {
Можно свой тип забабахать, смотри

```ts
type Nullable<T> = T | null;
```

```ts
button: Nullable<HTMLButtonElement>
```

2022-05-27 12:32 UTC, daria-bnn commented on src/ts/blocks-html/cards-element.ts
> +function cardsElement(card) {
Исправила

2022-05-27 12:33 UTC, daria-bnn commented on src/ts/blocks.ts
> +export function createButton(container: HTMLDivElement) {
Создала папку blocks и разбила функции по отдельным файлам)

2022-05-27 19:19 UTC, daria-bnn commented on src/styles/_global.scss
> +    src: url('../fonts/Rubik-VariableFont_wght.ttf');
Заменила на _woff_

2022-05-27 19:23 UTC, daria-bnn commented on src/styles/_first-page.scss
> +        border: 1px solid #757578;
Добавила для цветов переменные в отдельный файл __variables_

2022-05-27 19:31 UTC, daria-bnn commented on src/ts/blocks-html/result-block-element.ts
> +export function blockResult(image, result: string) {
Переименовала)

2022-05-27 22:22 UTC, daria-bnn commented on src/ts/blocks.ts
> +        inputs.forEach((input) => {
убрала это, повесила событие на общий блок формы

2022-05-27 22:23 UTC, daria-bnn commented on src/ts/blocks.ts
> +    const form: HTMLFormElement | null = container.querySelector('.form');
Тогда для form я удаляю тип

2022-05-27 22:23 UTC, daria-bnn commented on src/ts/blocks.ts
> +const ImgWin = require('../img/win.png');
Чудеса, но я сейчас попробовала еще раз настроить, как вы показывали на уроке и, кажется, работает!!) Ошибка исчезла. Добавила файл _index.d.ts_  в папку _src_. В конфиге прописала "include": ["./src/**/*.ts"]" (но, кажется, работает и без include)

2022-05-27 22:24 UTC, daria-bnn commented on src/ts/blocks.ts
> +const ImgWin = require('../img/win.png');
Чудеса, но я сейчас попробовала еще раз настроить, как вы показывали на уроке и, кажется, работает!!) Ошибка исчезла. Добавила файл _index.d.ts_  в папку _src_. В конфиге прописала "include": ["./src/**/*.ts"]" (но, кажется, работает и без include)

2022-05-27 22:31 UTC, daria-bnn commented on src/ts/create-cards-value.ts
> +function createCardValues(cardSuit: Card[], cardValue: string[]): CardResult[] {
исправила

2022-05-28 15:50 UTC, daria-bnn commented on src/ts/main-logic-game.ts
> +type OneCard = {
да точно) подправила

2022-05-28 17:32 UTC, daria-bnn commented on src/styles/_page-with-cards.scss
> +// .block-game__card-wrapper_background .card-block__background {
Правильно ли я понимаю, что в scss не должно быть закомментированного кода? Соответственно мне нужно добавить правило в stylelint? В документации к нему не могу найти ничего об этом((

2022-05-28 17:32 UTC, daria-bnn commented on src/ts/blocks.ts
> +                    input.value === 'light' ||
Ух, кажется не все понятным) попробовала применить "на минималках", не уверена, что в так. По смыслу получилось, как тоже, что если бы я объект сделала... (файл src/ts/blocks/create-form.ts)

2022-05-28 17:32 UTC, daria-bnn commented on src/ts/create-cards-value.ts
> +type Card = {
вынесла в отдельный файл

2022-05-28 17:33 UTC, daria-bnn commented on src/ts/index.ts
> +        application: any;
Создала тип App, Blocks, Screens. Но как не использовать в них any пока не могу разобраться(

2022-05-28 17:33 UTC, daria-bnn commented on src/ts/template-engine/create-template-card.ts
> +export function createTempleteCart(block: any) {
Создала _type HtmlEl_. И затипизировала все, что касается функций, которые возвращают объект, описывающий структуру html элементов. Но когда для шаблонизатора пытаюсь затипизировать аргумент block: HtmlEl сыпятся ошибки вот в таком духе 
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/102252954/170832504-1b783fa0-9d4e-4244-8c73-7fac34688cdb.png"> Кажется, шаблонизатор нужно переписывать, используя конструкции ts?

2022-05-28 17:33 UTC, daria-bnn commented on src/ts/utils/utils.ts
> +export function makeButtonInactive(button: HTMLButtonElement | null): void {
Класс, попробовала применить

2022-05-29 09:24 UTC, mrerberg commented on src/styles/_page-with-cards.scss
> +// .block-game__card-wrapper_background .card-block__background {
На самом деле не стоит заносить комменты в линтер, я попутал, так как комментарии могут быть нужны. Оставляй)

2022-05-29 09:25 UTC, mrerberg commented on src/ts/index.ts
> +        application: any;
А в чем трудности?

2022-05-29 09:26 UTC, mrerberg commented on src/ts/template-engine/create-template-card.ts
> +export function createTempleteCart(block: any) {
Тут просто надо написать четкий тип для структуры block. Так как этот аргумент же не стандартного типа, правильно? А кастомного?

2022-05-29 09:36 UTC, mrerberg requested changes

2022-05-29 09:36 UTC, mrerberg commented on src/ts/utils/utils.ts
> +export function makeButtonInactive(button: HTMLButtonElement | null): void {
А где попробовала? И успешно ли?

2022-05-29 09:36 UTC, mrerberg commented on src/ts/utils/utils.ts
> +export function makeButtonInactive(button: HTMLButtonElement | null): void {
Я вижу импорт, но не вижу использования

2022-05-29 09:36 UTC, mrerberg commented on src/ts/template-engine/create-template-card.ts
> +export function createTempleteCart(block: any) {
У тебя много ошибок, потому что `tag` в твоем типе опционален и ты не делаешь проверку на его наличие. 

```ts
if(block.tag) const result = document.createElement(block.tag)
```

2022-05-29 09:36 UTC, mrerberg commented on src/ts/types.ts
> +    image: any;
Прям any?

2022-05-29 09:36 UTC, mrerberg commented on src/ts/screens/game-page.ts
> +    const wrapper: HTMLDivElement | null =
Nullable<HTMLDivElement>?

2022-05-29 09:36 UTC, mrerberg commented on src/ts/blocks/create-form.ts
> +enum Levels {
Это бы вынести в какой-нибудь общий файл с константами, так как это можно переиспользовать

2022-05-29 09:36 UTC, mrerberg commented on src/ts/blocks/blocks-for-game-page/create-cards.ts
> +        '.block-cards__card-wrapper'
Кстати, я крайне не рекомендую завязываться логикой на классы. Это очень рыхлая и зыбкая конструкция. Используй лучше data атрибуты. Это надежно

2022-05-29 09:36 UTC, mrerberg commented on src/ts/blocks-html/form.ts
> +function blockForm(): HtmlEl {
export function

Поправь везде)

2022-05-29 11:16 UTC, daria-bnn commented on src/ts/blocks-html/form.ts
> +function blockForm(): HtmlEl {
Точно! вроде теперь везде избавилась от этого))

2022-05-29 11:16 UTC, daria-bnn commented on src/ts/screens/game-page.ts
> +    const wrapper: HTMLDivElement | null =
да точно, заменила на Nullable

2022-05-29 17:33 UTC, daria-bnn commented on src/ts/blocks/create-form.ts
> +enum Levels {
ок

2022-05-29 19:16 UTC, daria-bnn commented on src/ts/blocks/blocks-for-game-page/create-cards.ts
> +        '.block-cards__card-wrapper'
Попыталась перейти на дата атрибуты, если так все поняла. Насчет того что я на классы завязала все - уже настрадалась, когда как-то решила переименовать классы, а соотвественно и все логику пришлось править))

2022-05-29 19:50 UTC, daria-bnn commented on src/ts/types.ts
> +    image: any;
исправила))

2022-05-30 07:02 UTC, mrerberg requested changes

2022-05-30 07:02 UTC, mrerberg commented on src/ts/template-engine/create-template-card.ts
> +    block: HtmlEl | HtmlEl[] | string | (HtmlEl | string)[] | undefined
block?: HtmlEl | HtmlEl[] | string | (HtmlEl | string)[]

2022-05-30 07:02 UTC, mrerberg commented on src/ts/main-logic-game.ts
> +        '.block-timer__value-minute'
Я бы уменьшил завязку на классы и тут бы завязался на id. Оно редко будет меняться

2022-05-30 07:02 UTC, mrerberg commented on src/ts/main-logic-game.ts
> +        setTimeout(() => {
Я бы тело данной функции вынес бы по возможности в отдельную функцию

2022-05-30 07:02 UTC, mrerberg commented on src/ts/main-logic-game.ts
> +        '.block-timer__value-minute'
Дата атрибут или id?

2022-05-30 07:02 UTC, mrerberg commented on src/ts/create-cards-value.ts
> +        const infoAboutCardSpades: Card = {};
4 раза повторяется 1 и тот же код с небольшими изменениями. В функцию?

2022-05-30 07:02 UTC, mrerberg commented on src/ts/constants-for-game.ts
> +export enum Levels {
Можно просто файл constants назвать, поймут)

2022-05-31 07:11 UTC, mrerberg requested changes

2022-05-31 07:11 UTC, mrerberg commented on src/ts/template-engine/create-template-card.ts
> +    block?: HtmlEl | HtmlEl[] | string | (HtmlEl | string)[] | undefined
Если поставила знак вопроса, сам явный тип undefined можно убрать

2022-05-31 07:11 UTC, mrerberg commented on src/ts/main-logic/get-time.ts
> +        document.querySelector('#timer-value-sec');
querySelector -> getElementById

2022-05-31 07:11 UTC, mrerberg commented on src/ts/main-logic/get-random-array-cards.ts
> +    return randomArray;
Лучше сделать randomArray константой, а в конце сделать

```tsx
return [...randomArray].sort(() => Math.random() - 0.5);
```

2022-05-31 07:11 UTC, mrerberg commented on src/ts/main-logic/for-check-cards.ts
> +            firstCard = null;
Это можно тоже упрятать в функцию. Тут ты сбрасываешь пару карт. `resetSelectedCards()` или как-то так

2022-05-31 07:11 UTC, mrerberg commented on src/ts/main-logic/for-check-cards.ts
> +    window.attempt = numberOfattempt;
numberOfAttempt

2022-05-31 07:11 UTC, mrerberg commented on src/ts/create-cards-value.ts
> +        createObjCard(value, cardSuits, 0, arrayCard);
https://www.youtube.com/watch?v=ND8KQ5xjk7o

Про каррирование, интересно

2022-05-31 07:11 UTC, mrerberg commented on src/ts/create-cards-value.ts
> +function createObjCard(
createCard, этого вполне достаточно

2022-05-31 07:11 UTC, mrerberg commented on src/ts/create-cards-value.ts
> +    arrayCard.push(infoAboutCardSpades);
Лучше не меняй массив, пришедший в аргументах, это не совсем явное поведение, я бы карточку возвращал из функции и потом бы ее пихал в нужный массив

Потому что твоя функция своим названием ничего не говорит про то, что она куда-то карточку кидает после создания

2022-06-02 15:07 UTC, mrerberg approved these changes

2022-06-02 15:07 UTC, mrerberg commented on src/ts/template-engine/create-template-card.ts
> +    block?: HtmlEl | HtmlEl[] | string | (HtmlEl | string)[]
Тут дубль массива HtmlEl

```
HtmlEl[] | (HtmlEl | string)[]
```

2022-10-25 18:06 UTC, merged