Final version of the project
daria-bnn/the-card-game pull request #6
Opened 2022-06-04 16:41 UTC by daria-bnn

В проекте в **README** файл было добавлено описание игры. Также устранены ошибки в **ts-файлах** при строгом режиме типизации.

2022-06-05 09:16 UTC, mrerberg requested changes

2022-06-05 09:16 UTC, mrerberg commented on README.md
> +_JavaScript, TypeScript, SCSS, Webpack_
А что за _?

2022-06-05 09:16 UTC, mrerberg commented on src/ts/blocks/block-result-game/create-block-result.ts
> +export function createBlockLoss(container: HTMLDivElement) {
Лучше звучит `creteLossBlock`

2022-06-05 09:16 UTC, mrerberg commented on src/ts/blocks/blocks-for-game-page/create-cards.ts
> +    const startCheckCards = checkCards() as EventListener;
Прям так нужен as? К этому прибегать нужно в крайних случаях

2022-06-05 09:16 UTC, mrerberg commented on src/ts/blocks/create-form.ts
> +        '.block-options__input'
Когда работаешь с разметкой и завязывешь на нее логику, лучше ориентироваться на id или дата атрибуты, классы слишком зыбкие, непостоянные, могут без конца меняться

2022-06-05 09:16 UTC, mrerberg commented on src/ts/blocks/create-form.ts
> +                    input.value === Levels.Light ||
```
Object.values(Levels).includes(input.value)
```

2022-06-05 09:16 UTC, mrerberg commented on src/ts/blocks/create-form.ts
> +        const target = <HTMLElement>event.target;
А зачем тут дженерик? <HTMLElement>

2022-06-05 09:16 UTC, mrerberg commented on src/ts/constants.ts
> +    type = 'type',
Так ты же выше ключи с большой буквы именуешь

2022-06-05 09:30 UTC, daria-bnn commented on src/ts/blocks/block-result-game/create-block-result.ts
> +export function createBlockLoss(container: HTMLDivElement) {
Переименовала

2022-06-05 14:42 UTC, daria-bnn commented on src/ts/blocks/create-form.ts
> +        '.block-options__input'
Исправила тут. Завязывалась на классы, потому что на прошлых курсах предлагали использовать только классы, а на id и прочее не рекомендовали))
Лучше везде от них избавиться или же где-то их все-таки уместно образаться по классам?

2022-06-05 14:42 UTC, daria-bnn commented on src/ts/blocks/blocks-for-game-page/create-cards.ts
> +    const startCheckCards = checkCards() as EventListener;
В этой части получилось избавиться от as, указав тип для (event:MouseEvent) в функции с замыканием checkCards() _(файл ./main-logic/for-check-cards.ts)._ 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/102252954/172045604-6219aaad-4f6f-4858-a30c-e8def9cb74ad.png">
Нужно ли и тут избавляться от as HTMLDivElement. Просто если я тут это убираю, то выходит ошибка:
 ```sh
 Свойство "closest" не существует в типе "EventTarget". 
```

2022-06-05 15:16 UTC, daria-bnn commented on src/ts/blocks/create-form.ts
> +        const target = <HTMLElement>event.target;
Если не указываю тип принудительно (как я понимаю). То опять ошибка 
 ```sh
 Свойство "closest" не существует в типе "EventTarget".
```
Как от этого избавиться, в интернете нашла только способ и прописывать тип через as

<img width="602" alt="image" src="https://user-images.githubusercontent.com/102252954/172048717-6edaa397-5152-4526-aa5b-3f5c01cfebf1.png">

2022-06-05 15:36 UTC, daria-bnn commented on src/ts/constants.ts
> +    type = 'type',
да, исправила. Но уже не уверена, что мне этот объект нужен. я, используя его, пыталась решить проблему с типизацией в шаблонизаторе ```createTempleteCart(....)``` в части где работаю с атрибутами.  Если убираю свою сомнительную конструкцию, то получается вот что:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/102252954/172057157-e687b27f-25ab-4d8c-bc72-b350466f890a.png">
Выходит ошибка 
```
Элемент неявно имеет тип "any", так как выражение типа "string" не может использоваться для индексации типа "Attribute". В типе "Attribute" не обнаружена сигнатура индекса с параметром типа "string"
  ```
 Сломала голову как это исправить нормально. Получилось обойти проверку, через опять принудельным тип, но проблема не решена по сути
 ```
 if (block.attrs) {
        const keys = Object.keys(block.attrs);

        keys.forEach((key) => {
            const keyOne = key as keyof typeof block.attrs;
            if (block.attrs) {
                const value = block.attrs[keyOne];

                result.setAttribute(key, value);
            }
        });

2022-06-05 15:36 UTC, daria-bnn commented on src/ts/blocks/create-form.ts
> +                    input.value === Levels.Light ||
предложение, выглядит логично и просто, но когда я это применяю у меня выскакивают ошибки (2 скрин), связанные с типами и я никак их не могу побороть? Может быть где-то косяк в указании типа для объекта window.levelsGame
![image](https://user-images.githubusercontent.com/102252954/172057465-739780d3-b74f-4a5a-9ca6-64dd56657f1b.png)
ниже описала схожую проблему в файле с шаблонизатром при работе с атрибутами

2022-06-05 15:36 UTC, daria-bnn commented on README.md
> +_JavaScript, TypeScript, SCSS, Webpack_
выделила курсивом текст

2022-06-06 08:21 UTC, mrerberg commented on src/ts/blocks/create-form.ts
> +        '.block-options__input'
Классы для стилизации. Логику же лучше завязывать на id/data-атрибуты. Так как они менее изменчивы

2022-06-06 08:21 UTC, mrerberg commented on src/ts/blocks/create-form.ts
> +                    input.value === Levels.Light ||
Пока пропусти данное замечание

2022-06-06 08:22 UTC, mrerberg commented on src/ts/constants.ts
> +    type = 'type',
Так пойдет)

2022-06-06 08:25 UTC, mrerberg requested changes

2022-06-06 08:25 UTC, mrerberg commented on src/ts/types.ts
> +    'data-timer-value-sec'?: any;
Прям any?

2022-06-06 08:25 UTC, mrerberg commented on src/ts/blocks-html/cards-element.ts
> +            ['data-show-card']: 'true',
Строка true? Мб просто булевое значение?

2022-06-06 08:25 UTC, mrerberg commented on src/ts/types.ts
> +    'timer-value-sec'?: any;
any?

2022-06-06 20:28 UTC, daria-bnn commented on src/ts/types.ts
> +    'timer-value-sec'?: any;
убрала any везде

2022-06-06 20:34 UTC, daria-bnn commented on src/ts/blocks-html/cards-element.ts
> +            ['data-show-card']: 'true',
поставила булевое

2022-06-07 08:30 UTC, mrerberg approved these changes

2022-10-25 18:06 UTC, merged